# Generated by Django 5.2.6 on 2025-09-05 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cor",
            name="codigo",
            field=models.CharField(max_length=7, unique=True),
        ),
        migrations.AlterField(
            model_name="estado",
            name="sigla",
            field=models.CharField(max_length=2, unique=True),
        ),
        migrations.AlterField(
            model_name="regiao",
            name="sigla",
            field=models.CharField(max_length=2, unique=True),
        ),
        migrations.AlterField(
            model_name="tipoendereco",
            name="sigla",
            field=models.CharField(max_length=3, unique=True),
        ),
        migrations.AlterField(
            model_name="tipotelefone",
            name="sigla",
            field=models.CharField(max_length=3, unique=True),
        ),
    ]
